[build]
  command = "bash ./netlify-build.sh"
  publish = "build/web"

[[edge_functions]]
  function = "listing_share"
  path = "/listing/*"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
